### ISSUE TITLE
Fix jekyll rendering on github and STAB server.

### ISSUE THREAD

**Issue by rohitrango** [elec-club-iitb/website#30]
The design is broken somewhere i guess,
![elec club](https://cloud.githubusercontent.com/assets/15312514/16683175/0f0847a8-451c-11e6-80f2-60069c3a002b.png)

**Comment by udiboy1209** [comment]
The actual site is hosted on https://stab-iitb.org/electronics-club/ so jekyll is configured for that. I'll rename this issue to fix rendering on both.

**Comment by udiboy1209** [comment]
I think this was fixed here: [03303c](https://github.com/elec-club-iitb/website/commit/03303cfe08cdd4b5ba89dd1defb11fedcbbc9b53)
