### ISSUE TITLE
Make a Contact section

### ISSUE THREAD

**Issue by riddhishb** [elec-club-iitb/website#5]
Add links to fb, github and google group page, in the about us box on the right side

**Comment by udiboy1209** [comment]
Separate section would be better.

**Comment by riddhishb** [comment]
Fair enough

**Comment by udiboy1209** [comment]
Closed by [0c8a5e3](https://github.com/elec-club-iitb/elec-club-iitb.github.io/commit/0c8a5e3d41d89d1ebb930334befce06db2d158e1)
