### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by udiboy1209** [elec-club-iitb/website#6]
Looks very bad on mobile.

**Comment by CodeMaxx** [comment]
Main daalne vaala tha ye issue :P

**Comment by riddhishb** [comment]
Incorporating bootstrap will solve this!

**Comment by CodeMaxx** [comment]
@udiboy1209 You said it already has bootstrap -_-

**Comment by riddhishb** [comment]
Oh sorry bootstrap is there I am not sure why is it not responsive.

**Comment by CodeMaxx** [comment]
Bootstrap's classes have not been used in the code thats why.

**Comment by riddhishb** [comment]
@CodeMaxx My bad bro!

**Comment by udiboy1209** [comment]
[8bbdfc2](https://github.com/elec-club-iitb/elec-club-iitb.github.io/commit/8bbdfc23f68d765cf2e231b7699e786e24e09f4e) closes this. Was a broken link issue with the cdn used for bootstrap. changed to another cdn.
